version: '2'
services:
  labproject:
    depends_on:
      - db
      - zookeeper
      - kafka
    build: .
    container_name: labproject-springboot
    ports:
      - "8080:8080"
      - "4848:4848"
    expose:
      - "8080"
      - "4848"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/flights?useSSL=false

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: labproject-zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"


  kafka:
    image: wurstmeister/kafka
    container_name: labproject-kafka
    ports:
      - "9092:9092"
    expose:
      - "9902"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.28.0.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logs:1:1,data:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  db:
    image: mysql:5.6
    container_name: labproject-mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: pedro
      MYSQL_USER: pedro
      MYSQL_DATABASE: flights
      MYSQL_ROOT_HOST: '%'
    volumes:
      - c:\Docker\labproject\mysql:/var/lib/mysql

